var pages = [{'name': 'abstract class CompletableInteractor<P : InteractorParams>(ioScheduler: Scheduler, uiScheduler: Scheduler)', 'description':'reactivecircus.blueprint.interactor.rx2.CompletableInteractor', 'location':'blueprint-interactor-rx2/reactivecircus.blueprint.interactor.rx2/-completable-interactor/index.html', 'searchKey':'CompletableInteractor'},
{'name': 'fun CompletableInteractor(ioScheduler: Scheduler, uiScheduler: Scheduler)', 'description':'reactivecircus.blueprint.interactor.rx2.CompletableInteractor.CompletableInteractor', 'location':'blueprint-interactor-rx2/reactivecircus.blueprint.interactor.rx2/-completable-interactor/-completable-interactor.html', 'searchKey':'CompletableInteractor'},
{'name': 'fun buildCompletable(params: P): Completable', 'description':'reactivecircus.blueprint.interactor.rx2.CompletableInteractor.buildCompletable', 'location':'blueprint-interactor-rx2/reactivecircus.blueprint.interactor.rx2/-completable-interactor/build-completable.html', 'searchKey':'buildCompletable'},
{'name': 'abstract class ObservableInteractor<P : InteractorParams, T>(ioScheduler: Scheduler, uiScheduler: Scheduler)', 'description':'reactivecircus.blueprint.interactor.rx2.ObservableInteractor', 'location':'blueprint-interactor-rx2/reactivecircus.blueprint.interactor.rx2/-observable-interactor/index.html', 'searchKey':'ObservableInteractor'},
{'name': 'fun ObservableInteractor(ioScheduler: Scheduler, uiScheduler: Scheduler)', 'description':'reactivecircus.blueprint.interactor.rx2.ObservableInteractor.ObservableInteractor', 'location':'blueprint-interactor-rx2/reactivecircus.blueprint.interactor.rx2/-observable-interactor/-observable-interactor.html', 'searchKey':'ObservableInteractor'},
{'name': 'fun buildObservable(params: P): Observable<T>', 'description':'reactivecircus.blueprint.interactor.rx2.ObservableInteractor.buildObservable', 'location':'blueprint-interactor-rx2/reactivecircus.blueprint.interactor.rx2/-observable-interactor/build-observable.html', 'searchKey':'buildObservable'},
{'name': 'abstract class SingleInteractor<P : InteractorParams, T>(ioScheduler: Scheduler, uiScheduler: Scheduler)', 'description':'reactivecircus.blueprint.interactor.rx2.SingleInteractor', 'location':'blueprint-interactor-rx2/reactivecircus.blueprint.interactor.rx2/-single-interactor/index.html', 'searchKey':'SingleInteractor'},
{'name': 'fun SingleInteractor(ioScheduler: Scheduler, uiScheduler: Scheduler)', 'description':'reactivecircus.blueprint.interactor.rx2.SingleInteractor.SingleInteractor', 'location':'blueprint-interactor-rx2/reactivecircus.blueprint.interactor.rx2/-single-interactor/-single-interactor.html', 'searchKey':'SingleInteractor'},
{'name': 'fun buildSingle(params: P, blocking: Boolean): Single<T>', 'description':'reactivecircus.blueprint.interactor.rx2.SingleInteractor.buildSingle', 'location':'blueprint-interactor-rx2/reactivecircus.blueprint.interactor.rx2/-single-interactor/build-single.html', 'searchKey':'buildSingle'}]
